### ISSUE TITLE
SIGSEGV when using ecs server

### ISSUE THREAD

**Issue by timbz** [synfinatic/aws-sso-cli#1053] opened 2024-09-18 11:47 UTC
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.17.0 -- Copyright 2021-2024 Aaron Turner
8c32d5028c017fdfa9599756a7aea31b17f549a4 (v1.17.0) built at 2024-07-10T21:50:03+0000
```

**Describe the bug:**
Application crashes when starting ecs server

**To Reproduce:**
```
$ aws-sso ecs server
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xaab409]

goroutine 1 [running]:
main.(*EcsServerCmd).Run(0x1?, 0xc0002c2930)
	github.com/synfinatic/aws-sso-cli/cmd/aws-sso/ecs_server_cmd.go:72 +0x229
reflect.Value.call({0xb44100?, 0xc0003227e8?, 0xc28ec0?}, {0xc2b764, 0x4}, {0xc00011ef30, 0x1, 0x0?})
	reflect/value.go:596 +0xce7
reflect.Value.Call({0xb44100?, 0xc0003227e8?, 0xb63b40?}, {0xc00011ef30?, 0xc28ec0?, 0xc0002bec30?})
	reflect/value.go:380 +0xb9
github.com/alecthomas/kong.callFunction({0xb44100?, 0xc0003227e8?, 0x26?}, 0xc2b224?)
	github.com/alecthomas/kong@v0.9.0/callbacks.go:98 +0x40b
github.com/alecthomas/kong.(*Context).RunNode(0xc000122b00, 0xc00032d860, {0xc00052de80, 0x1, 0xc000380240?})
	github.com/alecthomas/kong@v0.9.0/context.go:774 +0x810
github.com/alecthomas/kong.(*Context).Run(0x0?, {0xc00052de80?, 0x0?, 0x0?})
	github.com/alecthomas/kong@v0.9.0/context.go:799 +0x132
main.main()
	github.com/synfinatic/aws-sso-cli/cmd/aws-sso/main.go:171 +0x5ae
```

**Expected behavior:**
No crash

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version 22.04

**Comment by synfinatic** [comment] 2024-09-18 15:05
duplicate of #1040   Fix will be in 2.0.0

**Closed by synfinatic** 2024-09-18 15:05 UTC
Labels: bug
