### ISSUE TITLE
Stop changing current working directory when entering/exiting shell environment

### ISSUE THREAD

**Issue by tommyalatalo** [synfinatic/aws-sso-cli#329] opened 2022-04-19 15:23 UTC
**Is your feature request related to a problem? Please describe.**
It's really annoying when the shell wrapper changes the current working directory after `sso exec` to assume a role, or `ctrl+D` to exit the wrapped environment.

**Describe the solution you'd like**
The shell wrapper should just remain in the directory that the console was in when `sso exec` or `ctrl+D` was executed.

**Comment by synfinatic** [comment] 2022-04-19 15:50
I can't reproduce this.  Any chance your `~/.bashrc` (or equivalent) isn't manually calling something like `cd $HOME` ?

**Comment by tommyalatalo** [comment] 2022-04-19 17:28
> 

No, I have no `cd` commands in my rc file, I'm using zsh though.

**Comment by synfinatic** [comment] 2022-04-19 20:32
okay, please provide more info... OS/version/etc.   because since I've never seen this, I'll need a way to verify I actually fix this.

**Comment by tommyalatalo** [comment] 2022-04-21 08:52
EndeavourOS (Arch)
aws-sso-cli:
```
❯ sso version
AWS SSO CLI Version 1.7.5 -- Copyright 2021-2022 Aaron Turner
32a73fac4dbab563f55e151f897178349435247b (v1.7.5) built at 2022-03-29T04:59:17-0700
```
zsh 5.8.1 (x86_64-pc-linux-gnu)
tmux 3.2a
alacritty 0.10.1 (2844606d)


I'm not sure what else would be relevant at this point. I just had this happen again, I ran `sso exec` to assume a new role, and got the error `FATAL   Unable to continue error="Conflicting environment variable 'AWS_ACCESS_KEY_ID' is set"` since the same terminal session had been used to assume another role previously. After pressing `ctrl+D` in this state the current working directory changes, to what I'm at this point assuming is the folder which `asso exec` was first run before the shell was wrapped.

**Comment by synfinatic** [comment] 2022-04-21 15:10
Oh, I  misunderstood you earlier when you said `CTRL+D`.  I didn't realize you were exiting the new shell- I thought you were still selecting a role to assume.

So yeah, it sounds like there is a misunderstanding how aws-sso works- if you are using `aws-sso exec` it spawns a new shell.  If in that shell you `cd` to another directory, when you exit that shell you will return to the directory you called `aws-sso exec` from.  That's just how shells work.

It sounds like what you really want is to not spawn a new shell.  Well, good news, you can do that- it's just a bit more convoluted because again, that's how shells work. 

So you have two options:
  1. Use the `eval` command: https://github.com/synfinatic/aws-sso-cli#eval
  2. Use the `config` command to generate the necessary config in your `~/.aws/config` file and just `export AWS_PROFILE=name-of-profile`: https://github.com/synfinatic/aws-sso-cli#config

**Comment by synfinatic** [comment] 2022-04-25 14:49
Hey @tommyalatalo, LMK if the above resolves your issue.  If I don't hear from you in a few days I'll close the ticket.

**Comment by tommyalatalo** [comment] 2022-04-25 20:03
The way I see it the above is not a very good workaround, seems like you lose the interactivity of the cli tool when you have to start manually exporting names of profiles?

**Comment by synfinatic** [comment] 2022-04-25 20:06
I agree it kinda sucks, but at the same time there isn't much I can do.  As I understand it, by design on Unix/POSIX systems, a sub-shell can't modify the parent shell without doing ugly hacks like the `eval` trick which of course limits the interactiveness.

Of course, if you know a magic trick to make this doable, please share.

**Comment by synfinatic** [comment] 2022-04-25 20:31
i should mention, you can always just do `aws-sso exec <command>`  and get interactive and commands, but of course that's a one command at a time thing which sucks in it's own way.

I suppose I could add a flag like `--last` where it just uses the last selected role so subsequent calls would be like:

`aws-sso exec --last <command>`

but still really hacky.

**Comment by tommyalatalo** [comment] 2022-04-25 22:13
I don't really have any tricks up my sleeve for this one, the first thing that comes to my mind is to somehow have an exit hook from the wrapping shell which would `cd` the underlying shell to the same directory that the `aws-sso` shell was last in.

**Comment by synfinatic** [comment] 2022-04-25 22:18
So that doesn't work unless you do the `eval` trick because `aws-sso` runs as a sub-process of the shell.  The shell has already fork()'d the `aws-sso` and so any state is lost- by design.

**Comment by synfinatic** [comment] 2022-04-26 15:23
Closing as wont-fix as issue is not possible and work arounds (albeit not perfect ones) do exist.

**Comment by synfinatic** [comment] 2022-05-02 22:43
@tommyalatalo So I played around with some scripts & alias commands and I think I have a cleaner way to do what you want.  Feel like playing with this code? https://github.com/synfinatic/aws-sso-cli/pull/358

There are some instructions in the updated quickstart guide: https://github.com/synfinatic/aws-sso-cli/blob/289c47c5c07f6f409a58363e106681ea62b468dc/docs/quickstart.md#installation

**Closed** 2022-05-07 03:06 UTC
Labels: duplicate, technical support
