### ISSUE TITLE
Error output "Too few fields for (role arn) History Tag: '' " when using an account with one role.

### ISSUE THREAD

**Issue by kevcube** [synfinatic/aws-sso-cli#305] opened 2022-03-17 17:40 UTC
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.7.4 -- Copyright 2021-2022 Aaron Turner
465eaafbcb29ea217e587a592ec5692937a3f176 (Homebrew) built at 2022-03-01T15:55:54+0000
```

**Describe the bug:**
when using a role that is the only role on that account, history item is saved with too few tags

```
❯ aws-sso version
ERRO[0000] Too few fields for arn:aws:iam::aws_account_id_redacted:role/AWSAdministratorAccess History Tag: '' 
ERRO[0000] Too few fields for arn:aws:iam::aws_account_id_redacted:role/AWSAdministratorAccess History Tag: '' 
ERROR   Too few fields for arn:aws:iam::aws_account_id_redacted:role/AWSAdministratorAccess History Tag: '' 
AWS SSO CLI Version 1.7.4 -- Copyright 2021-2022 Aaron Turner
465eaafbcb29ea217e587a592ec5692937a3f176 (Homebrew) built at 2022-03-01T15:55:54+0000
```

**To Reproduce:**
 1. Gain access to a SINGLE role on an account
 2. `aws-sso exec`
 3. in selector, choose `> AccountAlias ThisIsTheAccount` and press enter
 4. auth is successful, you get your `exec` shell, but subsequent `aws-sso` calls will spit out error

 **Expected behavior:**
* no error (maybe warning)
* maybe drop-from-history after first error occurrence
* proper add-to-history functionality

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 12.3

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
  Tenant:
    SSORegion: us-east-2
    StartUrl: https://d-redacted.awsapps.com/start
    DefaultRegion: us-east-2
DefaultSSO: Tenant
UrlAction: print 
LogLevel: warn
ConsoleDuration: 360
HistoryLimit: 10
HistoryMinutes: 1440
```

**Comment by synfinatic** [comment] 2022-03-23 15:03
@kevcube:

Wanted to give you a bit of an update.

First, the good news:

So this latest commit I think mostly fixes this issue.  It does this via two ways:

1. This log is now emitted at the `debug` level instead of `error` to better match the severity
2. When the `History` tag is empty, it is now skipped before being parsed.

At least in my testing, this should not only avoid the error messages being printed, but empty history tags should effectively be a no-op and execution should happen normally.  If you feel like pulling the latest from github it should be a lot better.

The not-so good news:

I'm not sure how `History` tags are being created with empty values.  With an empty `History` tag, previously selected roles will not show up when searching interactively by tag via the `exec` command, so I don't yet consider this a complete fix.

Lately I've been working on adding more unit tests and I plan to focus on this area of code to see if I can find the root cause.  With that in mind, i'm not yet closing this ticket.

**Closed** 2022-03-24 02:53 UTC
Labels: bug

**Comment by synfinatic** [comment] 2022-03-24 02:55
Found our little bug.  History tags were getting lost when the cache was refreshed with the latest AWS SSO metadata.  should be fixed now.
